name: Feature Request
description: Suggest an improvement or new capability
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the use case or frustration that led to this idea.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: What would you like to happen?
      description: Describe your ideal outcome. Be as specific or as vague as you like.
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
      description: Any workarounds or other approaches you've thought about.
    validations:
      required: false
